EverythingOpenSource/open-source-events

- README.md
Added Open Source events from February to June 2023
> Update FEB - JUNE README.md

- README.md
Signed-off-by: Akintola Rahmat <akintolarahmah@gmail.com>
> update readme with fluttercon event

- README.md
Hi folks!
Just adding our event, Mautic Conference India!  Thanks for curating the list! Should it also be added to the 2024 file?
> Add Mautic Conference India

- README.md
Hello! I am adding posit::conf(2024) from Posit (formerly RStudio), August 12-14 in Seattle, WA, USA. Thanks for considering!
> Add posit::conf(2024)

- README.md
Added an event in Gabrovo, Bulgaria
> Added an event in Gabrovo, Bulgaria

- README.md
Adds RubyConf 2024 to the schedule in November
> Add RubyConf 2024 in November

- README.md
> added flisol

- 2025events.md
Add edition 2025 of FOSDEM in Brussels, Belgium
> Add FOSDEM 2025 (Brussels, Belgium)

- README.md
> Pycom Namibia

- README.md
Adding FOSSASIA Summit in March
> Adding FOSSASIA Summit in March

- README.md
> added Flisol 2025

- README.md
Added the Laracon EU conference
> Add Laracon Eu

- README.md
I added EU Open Source Policy Summit happening on 31st Janaury online in Brussels
> add EU Open Source policy summit

- README.md
- contributing.md
This PR adds details about the FOSS Backstage Design, scheduled for 12th March 2025.
> FOSS Backstage Design 2025

- README.md
> Added PyCon Austria

- README.md
Updated to the right dates, 5th is a party and not part of the conference @mihrab34
> Update PyCon Austria dates

- README.md
Added PyTexas Conference @mihrab34
> Added PyTexas Conference

- README.md
khipu, pycon latam and latin R added.
> latam open source events added

- README.md
Added details about posit conference 2025
> added posit:conf 2025 details

- README.md
Added details on ShinyConf2025 : A global virtual conference focused on Shiny and data-driven applications. It features sessions on the latest tools, industry use cases, and best practices for building modern, scalable apps and it is hosted by Appsilon (https://www.appsilon.com/)
> added shinyconf2025

- README.md
> User r conference 2025

- README.md
Fix on OpenSearchCon Europe (removed improper space in name) 
Added OpenSearchCon India
thank you for hosting this list!
> OpenSearchCon Europe fix & India addition

- README.md
Adding OpenSearchCon North America to the listing. 
thank you
> add OpenSearchCon NA

- README.md
Updated the README with the ICS calendar link and steps to add it to various calendars (the popular ones)
> Add Calendar Subscrption Link

- README.md
PyOhio conference has been added to the July events for 2025
> Added the PyOhio event

- README.md
PyCon Taiwan added to the September Events
> Added the Pycon Taiwan event

- README.md
COSCUP (Conference for Open Source Coders, Users, and Promoters) has been added to the August events
> Added the COSCUP event

- README.md
I included OSCAFEST to the list of events
> Added OSCAFEST

- README.md
- Add PyCon Africa event to the README
> Add PyCon Africa event to the README

- README.md
- Add PyCon Togo event to the README
> Add PyCon Togo event to the README

- README.md
Pittsburgh TechFest 2025 is added to the October events
> Added Pittsburgh TechFest 2025

- README.md
Added the Carolina Code Conference 2025
> Added to the August events

- README.md
cfp is also opened 
https://pretalx.fossforall.org/2025/
> Add FOSS for All Conferrence 2025

- README.md
Added RSAA25 to September events
> Added RSAA25 event
